# Варіант №3
## Завдання №1 
Виконати набір вправ. Всі завдання виконати двома способами:
1) З використанням універсальних функцій бібліотеки NumPy
2) За допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
3) Для обох випадків підрахувати час виконання скрипту та зробити висновки
### 1) Вводиться число n. Вивести масив розміром n*n, в якому по діагоналі йдуть числа від 1 до n, а всі інші дорівнюють нулю.

In [6]:
import numpy as np

In [32]:
def readInputNumber(name = 'n'):
    return input(f"Введіть ціле число {(name)}: ")

In [54]:
def readInputArray():
    input_numbers = input("Введіть масив чисел (через пробіл): ");
    numbers = list(map(float, input_numbers.split()))
    return numbers

In [27]:
def print_matrix(matrix):
    for row in matrix:
        print(row)

In [34]:
%%time
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def diagonalMatrix(n):
    # [1, 2, .., n]
    numbers = np.arange(1, int(n) + 1, 1, dtype='int16');

    # matrix with zeros and the array on diagonal
    matrix = np.diag(numbers)
    return matrix

n = readInputNumber();
print(diagonalMatrix(n));

Введіть ціле число n:  8


[[1 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 5 0 0 0]
 [0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 8]]
CPU times: total: 0 ns
Wall time: 1.87 s


In [158]:
%%time
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def diagonalMatrix(n: int):
    n = int(n)
    matrix = [
        [0 for _ in range(n)] 
        for _ in range(n)
    ]
    for i in range(n):
        for j in range(n):
            if(i == j):
                matrix[i][j] = i + 1;
        
    return matrix

n = readInputNumber();
print_matrix(diagonalMatrix(n));

Введіть ціле число n:  8


[1, 0, 0, 0, 0, 0, 0, 0]
[0, 2, 0, 0, 0, 0, 0, 0]
[0, 0, 3, 0, 0, 0, 0, 0]
[0, 0, 0, 4, 0, 0, 0, 0]
[0, 0, 0, 0, 5, 0, 0, 0]
[0, 0, 0, 0, 0, 6, 0, 0]
[0, 0, 0, 0, 0, 0, 7, 0]
[0, 0, 0, 0, 0, 0, 0, 8]
CPU times: total: 0 ns
Wall time: 3.07 s


### 3) Вводяться чотири числа n, m, r, c. Вивести масив розміру n*m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [44]:
%%time
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def matrixOnes(n: int, m: int, r: int, c: int):
     matrix = np.ones((n, m), dtype='int16');
     matrix[r, :] = 0
     matrix[:, c] = 0
     print(matrix)

n = int(readInputNumber('n'));
m = int(readInputNumber('m'));
r = int(readInputNumber('r'));
c = int(readInputNumber('c'));

matrixOnes(n, m, r, c)

Введіть ціле число n:  7
Введіть ціле число m:  6
Введіть ціле число r:  5
Введіть ціле число c:  4


[[1 1 1 1 0 1]
 [1 1 1 1 0 1]
 [1 1 1 1 0 1]
 [1 1 1 1 0 1]
 [1 1 1 1 0 1]
 [0 0 0 0 0 0]
 [1 1 1 1 0 1]]
CPU times: total: 31.2 ms
Wall time: 2.41 s


In [46]:
%%time
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def matrixOnes(n: int, m: int, r: int, c: int):
    n = int(n)
    matrix = [
        [1 for _ in range(n)] 
        for _ in range(n)
    ]
    for i in range(n):
        for j in range(n):
            if(i == r or j == c):
                matrix[i][j] = 0;
        
    return matrix
    
n = int(readInputNumber('n'));
m = int(readInputNumber('m'));
r = int(readInputNumber('r'));
c = int(readInputNumber('c'));

print_matrix(matrixOnes(n, m, r, c));

Введіть ціле число n:  7
Введіть ціле число m:  6
Введіть ціле число r:  5
Введіть ціле число c:  4


[1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 0, 1, 1]
[0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 1, 1]
CPU times: total: 15.6 ms
Wall time: 3.04 s


### 6) З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.

In [62]:
%%time
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def notZeroToMinusOne(arr):
    array = np.array(arr);
    array[array != 0] = -1
    return array

arr = readInputArray()
notZeroToMinusOne(arr)

Введіть масив чисел (через пробіл):   2 3 0 7 8 0 9.86 3.4 98 0 22.1


CPU times: total: 0 ns
Wall time: 1.7 s


array([-1., -1.,  0., -1., -1.,  0., -1., -1., -1.,  0., -1.])

In [63]:
%%time
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def notZeroToMinusOne(arr):
    size = len(arr)
    for i in range(size):
        if(arr[i] != 0):
            arr[i] = -1.0;
    return arr        

arr = readInputArray()
notZeroToMinusOne(arr)

Введіть масив чисел (через пробіл):   2 3 0 7 8 0 9.86 3.4 98 0 22.1


CPU times: total: 0 ns
Wall time: 1.94 s


[-1.0, -1.0, 0.0, -1.0, -1.0, 0.0, -1.0, -1.0, -1.0, 0.0, -1.0]

### 7) З клавіатури вводиться масив. Замінити всі нульові елементи на -1.

In [64]:
%%time
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def zeroToMinusOne(arr):
    array = np.array(arr);
    array[array == 0] = -1
    return array

arr = readInputArray()
zeroToMinusOne(arr)

Введіть масив чисел (через пробіл):  2 3 0 7 8 0 9.86 3.4 98 0 22.1


CPU times: total: 0 ns
Wall time: 1.8 s


array([ 2.  ,  3.  , -1.  ,  7.  ,  8.  , -1.  ,  9.86,  3.4 , 98.  ,
       -1.  , 22.1 ])

In [67]:
%%time
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def notZeroToMinusOne(arr):
    size = len(arr)
    for i in range(size):
        if(arr[i] == 0):
            arr[i] = -1.0;
    return arr        

arr = readInputArray()
notZeroToMinusOne(arr)

Введіть масив чисел (через пробіл):  2 3 0 7 8 0 9.86 3.4 98 0 22.1


CPU times: total: 0 ns
Wall time: 2.62 s


[2.0, 3.0, -1.0, 7.0, 8.0, -1.0, 9.86, 3.4, 98.0, -1.0, 22.1]

### 8) З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.

In [72]:
%%time
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def countZerosNotZeros(arr):
    array = np.array(arr);
    zeros = array[array == 0]
    notZeros = array[array != 0]
    return {
        'Нулів': len(zeros),
        'Не нулів': len(notZeros)
    }

arr = readInputArray()
countZerosNotZeros(arr)

Введіть масив чисел (через пробіл):   2 3 0 7 8 0 9.86 3.4 98 0 22.1


CPU times: total: 15.6 ms
Wall time: 1.36 s


{'Нулів': 3, 'Не нулів': 8}

In [77]:
%%time
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def countZerosNotZeros(arr):
    size = len(arr)
    zeros = 0;
    notZeros = 0;
    for i in range(size):
        if(arr[i] == 0):
            zeros += 1
        else: notZeros += 1
    return {
        'Нулів': zeros,
        'Не нулів': notZeros
    }

arr = readInputArray()
countZerosNotZeros(arr)

Введіть масив чисел (через пробіл):  2 3 0 7 8 0 9.86 3.4 98 0 22.1


CPU times: total: 0 ns
Wall time: 1.6 s


{'Нулів': 3, 'Не нулів': 8}

### 11) Створити масив з одиниць розміром n*n та додати до нього рамку, що утворюється з 0.

In [81]:
%%time
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def onesInsideZerosBorder(n: int):
    matrixOnes = np.ones((n, n));
    largerZerosMatrix = np.zeros((n + 2, n + 2) , dtype=int);
    largerZerosMatrix[1:n + 1, 1:n + 1] = matrixOnes
    return largerZerosMatrix;

n = int(readInputNumber('n'));
print(onesInsideZerosBorder(n));

Введіть ціле число n:  5


[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 1.48 s


In [93]:
%%time
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def onesInsideZerosBorder(n: int):
    n = int(n)
    matrixZeros = [
        [0 for _ in range(n + 2)] 
        for _ in range(n + 2)
    ]
    for i in range(n + 2):
        for j in range(n + 2):
            if(i > 0 and j > 0 and i < n + 1 and j < n + 1):
                matrixZeros[i][j] = 1;
        
    return matrixZeros

n = int(readInputNumber('n'));
print_matrix(onesInsideZerosBorder(n));

Введіть ціле число n:  5


[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 1.26 s


### 16) Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [96]:
%%time
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def populateVectore(n: int):
    vector = np.arange(0, n + 1, 1);
    condition = np.logical_and(vector > n/4, vector < 3*n/4)
    vector[condition] = 0
    return vector;

# n = 9 => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] => [0, 1, 2, 0, 0, 0, 0, 7, 8, 9]
n = int(readInputNumber('n'));
print(populateVectore(n));

Введіть ціле число n:  9


[0 1 2 0 0 0 0 7 8 9]
CPU times: total: 0 ns
Wall time: 1.92 s


In [98]:
%%time
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def populateVectore(n: int):
    vector = [i for i in range(n + 1)]
    cond1 = n/4;
    cond2 = 3*n/4;
    for i in range(n):
        if(vector[i] > cond1 and vector[i] < cond2):
            vector[i] = 0
    return vector;

# n = 9 => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] => [0, 1, 2, 0, 0, 0, 0, 7, 8, 9]
n = int(readInputNumber('n'));
print(populateVectore(n));

Введіть ціле число n:  9


[0, 1, 2, 0, 0, 0, 0, 7, 8, 9]
CPU times: total: 0 ns
Wall time: 2.02 s


### 18) Згенерувати вектор з n випадкових чисел від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [102]:
%%time
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def generateVectore(n: int):
    vector = np.random.randint(0, 99, n);
    unique = np.unique(vector);
    return {
        'Послідовність': vector,
        'Кількість унікальних чисел': len(unique)
    };

n = int(readInputNumber('n'));
print(generateVectore(n));

Введіть ціле число n:  5


{'Послідовність': array([44, 66, 63,  7, 21]), 'Кількість унікальних чисел': 5}
CPU times: total: 0 ns
Wall time: 1.64 s


In [103]:
%%time
import random
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def generateVectore(n: int):
    vector = [random.randint(0, 99) for _ in range(n)];
    unique = set(vector);
    return {
        'Послідовність': vector,
        'Кількість унікальних чисел': len(unique)
    };

n = int(readInputNumber('n'));
print(generateVectore(n));

Введіть ціле число n:  5


{'Послідовність': [11, 35, 74, 48, 11], 'Кількість унікальних чисел': 4}
CPU times: total: 31.2 ms
Wall time: 2.65 s


### 19) Згенерувати вектор із n елементів, які рівномірно розміщені на інтервалі (0, 1), тобто обидва кінці інтервалу не включені. Значення вивести до трьох знаків після коми.

In [111]:
%%time
%precision 3
# Спосіб реалізації за рахунок використання УНІВЕРСАЛЬНИХ ФУНКЦІЙ бібліотеки NumPy
def generateVectorRandom(n: int):
    vector = np.random.random(n);
    return vector;

# n = 9 => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] => [0, 1, 2, 0, 0, 0, 0, 7, 8, 9]
n = int(readInputNumber('n'));
print(generateVectorRandom(n));

Введіть ціле число n:  10


[0.576 0.324 0.395 0.82  0.419 0.615 0.847 0.421 0.376 0.237]
CPU times: total: 0 ns
Wall time: 1.51 s


In [116]:
%%time
%precision 3
import random
# Спосіб реалізації за рахунок використання ІТЕРАТИВНИХ методів
def generateVectorRandom(n: int):
    vector = [round(random.random(), 3) for _ in range(n)];
    return vector;

n = int(readInputNumber('n'));
print(generateVectorRandom(n));

Введіть ціле число n:  10


[0.869, 0.665, 0.366, 0.816, 0.759, 0.389, 0.733, 0.741, 0.182, 0.392]
CPU times: total: 15.6 ms
Wall time: 2.96 s


## Завдання №2

### Розв'язати систему алгебраїчних рівнянь з використанням формул Крамера й виконати перевірку за допомогою:
1) Матричного множення
2) Оберненої матриці
3) Функції `numpy.linalg.solve()`

Порівняти всі рішення за допомогою функції `numpy.allclose()`


\begin{equation}
\begin{cases}
    x_1 + 2x_2 + 3x_3 + 4x_4 &= 5 \\
    2x_1 + x_2 + 2x_3 + 3x_4 &= 1 \\
    3x_1 + 2x_2 + x_3 + 2x_4 &= 1 \\
    4x_1 + 3x_2 + 2x_3 + x_4 &= -5
\end{cases}
\end{equation}

In [124]:
# Задані коефіцієнти системи
coefficients = [
    [1, 2, 3, 4],
    [2, 1, 2, 3],
    [3, 2, 1, 2],
    [4, 3, 2, 1]
];
constants = [5, 1, 1, -5];

# Розв'язання за допомогою формул Крамера
def solve_system_cramer(coefficients, constants):
    main_determinant = np.linalg.det(coefficients)

    if main_determinant == 0:
        raise ValueError("Система рівнянь не має єдиного розв'язку.")

    solutions = []
    for i in range(len(coefficients)):
        modified_matrix = np.copy(coefficients)
        modified_matrix[:, i] = constants
        solutions.append(round((np.linalg.det(modified_matrix) / main_determinant), 3))

    return solutions

# Розв'язання за допомогою матричного множення
def solve_system_matrix_multiplication(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    solutions = np.dot(inverse_matrix, constants)
    return solutions

# Розв'язання за допомогою функції numpy.linalg.solve()
def solve_system_numpy(coefficients, constants):
    solutions = np.linalg.solve(coefficients, constants)
    return solutions

# Розв'язки за допомогою різних методів
cramer_solutions = solve_system_cramer(coefficients, constants)
matrix_multiplication_solutions = solve_system_matrix_multiplication(coefficients, constants)
numpy_solutions = solve_system_numpy(coefficients, constants)

# Порівняння розв'язків за допомогою numpy.allclose()
are_close_cramer_matrix = np.allclose(cramer_solutions, matrix_multiplication_solutions)
are_close_cramer_numpy = np.allclose(cramer_solutions, numpy_solutions)

# Вивід результатів
print("Розв'язки за допомогою Крамера:", cramer_solutions)
print("Розв'язки за допомогою матричного множення:", matrix_multiplication_solutions)
print("Розв'язки за допомогою numpy.linalg.solve():", numpy_solutions)

# Вивід порівняння
print("\nПорівняння Крамера і матричного множення:", are_close_cramer_matrix)
print("Порівняння Крамера і numpy.linalg.solve():", are_close_cramer_numpy)


Розв'язки за допомогою Крамера: [-2.0, 2.0, -3.0, 3.0]
Розв'язки за допомогою матричного множення: [-2.  2. -3.  3.]
Розв'язки за допомогою numpy.linalg.solve(): [-2.  2. -3.  3.]

Порівняння Крамера і матричного множення: True
Порівняння Крамера і numpy.linalg.solve(): True


## Завдання №3

### Обчислити значення матричного виразу:
1) З використанням універсальних функцій бібліотеки NumPy
2) За допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
3) Для обох випадків підрахувати час виконання скрипту та зробити висновки

Порівняти всі рішення за допомогою функції `numpy.allclose()`

\begin{equation}
    2(A - B)(A^{2} + B)
\end{equation}


$$ A = 
\begin{bmatrix}
    5 & 1 & 7 \\
    -10 & -2 & 1 \\
    0 & 1 & 2 \\
\end{bmatrix}
$$

$$ B = 
\begin{bmatrix}
    2 & 4 & 1 \\
    3 & 1 & 0 \\
    7 & 2 & 1 \\
\end{bmatrix}
$$

In [140]:
# Define matrices A and B
A = [[5, 1, 7], 
    [-10, -2, 1], 
    [0, 1, 2]]

B = [[2, 4, 1], 
    [3, 1, 0], 
    [7, 2, 1]]

In [152]:
%%time
# NumPy approach using universal functions
def compute_expression_numpy(A, B):
    A = np.array(A)
    B = np.array(B)
    return 2 * np.multiply(np.subtract(A, B), np.add(np.square(A), B))

result_numpy = compute_expression_numpy(A, B)
print("Result using NumPy:\n", result_numpy)

Result using NumPy:
 [[  162   -30   600]
 [-2678   -30     2]
 [  -98    -6    10]]
CPU times: total: 0 ns
Wall time: 993 µs


In [154]:
%%time
# Iterative approach
def compute_expression_iterative(A, B):
    rows, cols = len(A), len(A[0])
    result = [[0] * cols for _ in range(rows)]
    
    for i in range(rows):
        for j in range(cols):
            result[i][j] = 2 * (A[i][j] - B[i][j]) * (A[i][j]**2 + B[i][j])
            
    return result

result_iterative = compute_expression_iterative(A.tolist(), B.tolist())
print("\nResult using Iterative approach:\n", end='')
print_matrix(result_iterative)


Result using Iterative approach:
[162, -30, 600]
[-2678, -30, 2]
[-98, -6, 10]
CPU times: total: 0 ns
Wall time: 998 µs


In [157]:
comparison = np.allclose(result_numpy, result_iterative)
print('Comparizon of the solutions NumPy vs Iterative: ', end='')
print(comparison);

Comparizon of the solutions NumPy vs Iterative: True
